name: codefordaysweb
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  universal_html: ^1.1.20

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/profile_pics/josh.png
    - assets/profile_pics/ashley.jpeg
    - assets/profile_pics/than.jpeg